### ISSUE TITLE
"pickle.loads(data=data_stream)" raises TypeError, in SMOS_utils.py, line 336

### ISSUE THREAD

**Issue by ISA233** [AntonyMei/SharedMemoryObjectStore#1] opened 2022-04-06 10:01 UTC
It seems that the `deserialized_object = pickle.loads(data=data_stream)` in the `SMOS_utils.py` file throws an error when using python3.9 or higher. The error message is:

```Python
TypeError: loads() takes exactly 1 positional argument (0 given)
```

The reason might be that after python3.9, the parameter of `pickle.loads` function is no longer called `data`. After removing the `data=`, the code works fine.

**Comment by AntonyMei** [comment] 2022-04-06 14:51
Thanks a lot for the bug report. The problem is recognized and fixed in version `1.4.2`.

**Closed as completed by AntonyMei** 2022-04-06 14:51 UTC
